### ISSUE TITLE
Is there anyway to get glyph name?

### ISSUE THREAD

**Issue by NovaDev94** [devongovett/fontkit#33]
Currently, I have a need of getting a glyph name from a glyph / glyph id. That can be easily done in other font-related libraries (in other languages, yeah).  

However I found the `font.post.names` doesn't return correct glyph name and also its length doesn't match the total number of glyphs. Trying out in conjunction with `font.post.glyphNameIndex` doesn't work also.    

Is there an official way to do it? Or how can I achieve that?

**Comment by devongovett** [comment]
The `post` table doesn't contain all of the glyph names because the first 258 names are specified in a static list, and only glyphs not in that list are specified in the font. See [here](https://developer.apple.com/fonts/TrueType-Reference-Manual/RM06/Chap6post.html) for docs. I will work on adding a `name` property to glyph objects to make this easier.

**Comment by devongovett** [comment]
Glyph objects now have a `name` property as of #34. Uses the `post` table for TrueType fonts, and the CFF charset for CFF fonts.
