### ISSUE TITLE
Why is this project being developed? :) 

### ISSUE THREAD

**Issue by davelab6** [devongovett/fontkit#4]
I'm curious what the context of this project is; opentype.js seems to predate it and do most of what it does, so I wonder why you guys didn't contribute to that but start yet another sfnt js library :)

**Comment by devongovett** [comment]
This project existed as part of [PDFKit](http://github.com/devongovett/pdfkit) for many years (since 2011) and I'm just getting around to extracting it as a separate project. I've also added a ton of features for advanced typography that were previously not supported by PDFKit, and I'll be switching PDFKit over to fontkit soon (there's already a working branch).

As for features compared to opentype.js (which I only saw recently - not sure how long it's been around), fontkit seems to have much greater support for advanced layout features (both OpenType and Apple Advanced Typography), support for more font formats (ttf, otf, woff, woff2, ttc, and dfont), support for more glyph types (e.g. color emoji formats), support for almost all OpenType/TrueType/AAT [tables](https://github.com/devongovett/fontkit/tree/master/src/tables), and supports subsetting fonts with both PostScript and TrueType glyphs. Both support reading glyphs and converting them to vector paths, etc.
