### ISSUE TITLE
Glyph not reposition correctly, GPOS not apply

### ISSUE THREAD

**Issue by saknarak** [devongovett/fontkit#71]
When I create pdf with ttf font that has GPOS table.
Glyph not reposition correctly

Maybe it's fontkit issue

sample codepoint seq
0x0E14 0x0E35 0x0E1B 0x0E35

![image](https://cloud.githubusercontent.com/assets/7794793/23007250/f51fd9aa-f439-11e6-9120-d866b6c15293.png)

**Comment by Pomax** [comment]
Which specific font (name + version + font maker) is this for?

**Comment by saknarak** [comment]
This is national standard font of Thailand. I use it many times with pdfkit < 0.8 without problem.

"TH Sarabun New"
You can try this font

[THSarabunNew.zip](https://github.com/devongovett/fontkit/files/781056/THSarabunNew.zip)

**Comment by devongovett** [comment]
Old PDFKit did not use fontkit, and thus did not apply GPOS. New PDFKit uses fontkit, but we don't have a thai shaper yet, so it is using the default shaper, which may be misbehaving here.

**Comment by devongovett** [comment]
Turns out this font is actually an AAT font (i.e. it has a `morx` table). However, we were still applying fallback positioning using unicode properties. As of d357519fec455e9cb0148968907ff16fa0c84f13, I have turned this off for AAT fonts. Now it will only be applied if there is both no AAT and no GPOS support.

Published in v0.6.1.

**Comment by saknarak** [comment]
It's working now. Thank you very much for your effort.
