### ISSUE TITLE
Fonts without postscript name fails

### ISSUE THREAD

**Issue by tspiva** [devongovett/fontkit#73]
If a TTF or Woff font doesn't have a postscript name and you try to use it, an exception is thrown.  The error occurs at TTFFont.js "get postscriptName()" method.  Adding a null pointer check fixes it. I will do a pull request also.

**Comment by Pomax** [comment]
Note that a TTF without a name string 6 is "legal according to the spec, but illegal according to Operating Systems". You can't install a TTF without a postscript name, and Adobe's tooling certainly won't let you use an OpenType font without a postscript name. 

For WOFF the lack of a postscript name is less problematic since `@font-face` rules don't need postscript names, but then WOFF are literally optimized for loading by browsers. You won't find a WOFF in a PDF file, for instance, that wouldn't make any sense =)

**Comment by tspiva** [comment]
While I don't know if are legal or not, we have several fonts without them.  They were gathered from various places and licensed but don't include that information.  We've tried to fix them with FontForge but couldn't get them to work right either so we fixed it here with this line of code.

All of our WOFF fonts started out at TTF and converted to WOFF for use.

**Comment by Pomax** [comment]
That sounds quite curious, but those TTF cannot be installed for use on Windows, for instance. Almost all font tools will auto-generate ids 1 through 6 because they're so critical, so having TTF without them is more than a little curious. That said, you can edit one in almost trivially with [TTX](https://github.com/fonttools/fonttools): serialize the font to XML, add a name string with id 6, and reserialize to ttf.

**Comment by tspiva** [comment]
Our use case is using PDFKit in a browser which is why we are using WOFF files.

**Comment by devongovett** [comment]
Curious about this. Can you link to the fonts you're using, or send them to my email? I'm devongovett@gmail.com.

**Comment by liborm85** [comment]
With font Wingdings 2 (download compressed file: [wingdings2.ttf.gz](https://github.com/devongovett/fontkit/files/957425/wingdings2.ttf.gz) ) will cause failure in postscriptName method because `this.name` is undefined.

@devongovett Can you look it and fix? Thanks.
  
Related issue in pdfmake: https://github.com/bpampuch/pdfmake/issues/966

**Comment by natcohen** [comment]
@devongovett Any chance you can have a look at this?

**Comment by Pomax** [comment]
Note that there are *tons* of errors in this font according to [Font Validator](https://github.com/hintak/Font-Validator). Looking at the TTX dump, this looks like some (questionably legal) derivative of the real Mircosoft WinDings font, so I guess my first question is "how did you even get this font, it's preeeetty broken, and almost certainly illegal" =)

**Comment by devongovett** [comment]
What happened here was that the `name` table contained strings in several different encodings, one of which was unsupported by `iconv-lite`, which threw an error. This caused the `name` table not to be decoded properly. I added a catch for those errors in restructure: https://github.com/devongovett/restructure/commit/c6c2f10bfd35c628087a486136ba4ae6209209e6.

Additionally, since there were multiple encodings, one of them returned a buffer instead of a string since it could not be decoded. This version overrode the other encoding which was properly decoded. I added a check to fontkit to prefer fully decoded strings over buffers. https://github.com/devongovett/fontkit/commit/ff92ff56f807abed8a3994bea9f6add05f035264.

Published in v1.5.5. Please try it out!

**Comment by natcohen** [comment]
@Pomax I got this font straight from Microsoft through windows 10 and office 2016! Try with yours and you'll see...

@devongovett & @liborm85 will try it as soon as it gets implemented in pdfmake! Thanks

**Comment by liborm85** [comment]
@devongovett Thanks. I'm tested new fontkit version in pdfmake and pdfkit, there is now no throw error, but was rendered wrong pdf files:
![pdf-screen](https://cloud.githubusercontent.com/assets/1298652/25577539/13950bb4-2e67-11e7-83bb-8b49c44e92ed.png)

Here is my test scripts with output pdf files: [font-tests.zip](https://github.com/devongovett/fontkit/files/967654/font-tests.zip)

**Comment by Pomax** [comment]
@natochen windows 10 only comes with webdings.ttf and wingdings.ttf - there is no windings2.ttf, so you must have gotten that from somewhere else. Use the normal wingdings.ttf and you should be fine.

**Comment by natcohen** [comment]
@Pomax wingdings 2 is an official font provided by Microsoft (https://www.fonts.com/font/microsoft-corporation/wingdings/2)! You may or may not have noticed that wingdings and wingdings 2 are two completly different fonts. I need the checkbox of wingdings 2, wingdings is totally useless for me...

I've found the font in windows folders but it was probably added by office 2016 (that's why I thought it was also in windows 10)

@liborm85 & @devongovett does it work now?

**Comment by Pomax** [comment]
@natcohen as per https://www.microsoft.com/typography/fonts/font.aspx?FMID=665 that font does not come "with windows", it comes with several other applications instead (or can be purchased for free) but I would highly doubt that a font by Microsoft has this many errors in it. Are you sure you're working with the official version?

**Comment by natcohen** [comment]
@Pomax this list is definitely not exhaustive or they just forgot to update it for office 2016. You can check yourself and either download the official version or take it from your own font folder and you'll see... instead of arguing you can verify yourself.

The question remains open: will this don't be supported any time soon?

**Comment by devongovett** [comment]
@natcohen @liborm85 ran your test and it's fixed in v1.5.7 via 6ae0d049a0ca9a708cf90d5a88411db9200bda74.

This was an unrelated issue to postscript names which were already fixed above. There are two cmap subtables in that font. One used a "symbol" encoding (not sure exactly what encoding it is really, some windows thing), and the other used the Mac Roman encoding. We were choosing the symbol encoding, but it wasn't really supported. We now choose the Mac Roman encoding if you also install `iconv-lite` alongside fontkit to extend its encoding support. Unfortunately, the font has no unicode cmap, so this will be necessary to make it work.

**Comment by natcohen** [comment]
@liborm85 Do I simply have to include iconv-lite in my `index.html` of should I do something when I build pdfmake?

**Comment by Pomax** [comment]
@devongovett the `Symbol` encoding is for fonts that do not contain "letters" but only contain icons/graphics, potentially even using codepoints normally reserved for letters rather than PUA. Microsoft's not the only one who does this, but wingdings is certainly the archetypical font for it. New (and recent) fonts have been encouraged to use Unicode and put any iconography in PUA but older symbol fonts are typically 3/0.

So it's not really a "text" encoding, so it probably makes sense to bypass iconv entirely when a Symbol cmap is encountered, rather than relying on iconv-lite.

**Comment by natcohen** [comment]
@devongovett & @liborm85 Everything works for me...

**Comment by devongovett** [comment]
@Pomax the problem is that we need a mapping from symbol to unicode, so that "A" maps to whatever symbol is supposed to be displayed. `iconv-lite` doesn't have such a mapping, which is why I ignored that encoding and used a fallback one in the font (Mac roman).

**Comment by Pomax** [comment]
Hm, perhaps not the right issue to discuss this further, but: why is that necessary? There is no text to support for a Symbol font, so the mapping is just a 1:1 map between glyphid and whatever the document codepage/encoding is, without any conversion.
