### ISSUE TITLE
Get font-weight value

### ISSUE THREAD

**Issue by swampthang** [devongovett/fontkit#78]
Where in the font object would I look to obtain a font-weight value as a number (400, 500, etc) or a string (bold, normal, etc)

Also, is there something that would tell me if the font is a monospace?

**Comment by Pomax** [comment]
as long as you understand that font weights are *not* CSS font weights, you can query the OS/2 table for `usWeightClass` (https://www.microsoft.com/typography/otspec/os2.htm#wtc). Note that in OpenType-land this is *not* the same as the font style classification: you can have a normal font with weight 999 or a bold font with weight 1. There is no specification-defined relation between the two. The subfamily string for the font (regular, italic, bold, bold italic) can be found in the name table, as name record with id 2 (*if* supplied in the font. It might be missing). The is also the OS/2 table's fsSelection value that overlaps with that, https://www.microsoft.com/typography/otspec/os2.htm#fst.

Finally, to tell if a font is monospaced, you can check the `bProportion` bit in the Panose classification (https://www.microsoft.com/typography/otspec/os2.htm#pan) but this is not super reliable. You can also check the "post" table for the `isFixedPitch` value (https://www.microsoft.com/typography/otspec/post.htm). And finally, you can check the "hmtx" table (https://www.microsoft.com/typography/otspec/hmtx.htm) because if your font is truly monospaced, there is only one horizontal metric value instead of a large number of different widths for (ranges of) glyph(s).

**Comment by swampthang** [comment]
Thanks a bunch, Pomax. Much appreciated.

**Comment by Modi34** [comment]
Had the same problem. Was able to detect usWeightClass for .otf, .ttf files using https://opentype.js.org/font-inspector.html
![](https://i.imgur.com/myUTstN.png)
